version: '3.9'

services:


  app:
    hostname: app
    container_name: app
    restart: always
    build: 
      context: ./app/
      dockerfile: Dockerfile
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/home/app
    ports:
      - "8000:8000"
    networks:
      - net
    env_file:
      - .env
    depends_on:
      - postgres


  postgres:

    image: postgres:15.4-alpine  
    hostname: postgres  
    container_name: postgres  
    restart: on-failure
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - net
    volumes:  
      - postgres:/var/lib/postgresql/data


  pgadmin:

    image: dpage/pgadmin4
    hostname: pgadmin
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - net
    depends_on:
      - postgres

volumes:
  postgres:
    driver: local

networks:
  net:
    external: true