"""initial migration

Revision ID: b45daeef0786
Revises: 1691b9877529
Create Date: 2023-11-09 19:37:15.843922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b45daeef0786'
down_revision: Union[str, None] = '1691b9877529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_type', sa.Column('type', sa.String(), nullable=True))
    op.drop_column('exercise_type', 'name')
    op.add_column('set', sa.Column('previous_set_id', sa.Integer(), nullable=True))
    op.add_column('set', sa.Column('next_set_id', sa.Integer(), nullable=True))
    op.drop_constraint('set_parent_superset_id_fkey', 'set', type_='foreignkey')
    op.drop_constraint('set_child_superset_id_fkey', 'set', type_='foreignkey')
    op.create_foreign_key(None, 'set', 'set', ['next_set_id'], ['id'])
    op.create_foreign_key(None, 'set', 'set', ['previous_set_id'], ['id'])
    op.drop_column('set', 'parent_superset_id')
    op.drop_column('set', 'child_superset_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('set', sa.Column('child_superset_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('set', sa.Column('parent_superset_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'set', type_='foreignkey')
    op.drop_constraint(None, 'set', type_='foreignkey')
    op.create_foreign_key('set_child_superset_id_fkey', 'set', 'set', ['child_superset_id'], ['id'])
    op.create_foreign_key('set_parent_superset_id_fkey', 'set', 'set', ['parent_superset_id'], ['id'])
    op.drop_column('set', 'next_set_id')
    op.drop_column('set', 'previous_set_id')
    op.add_column('exercise_type', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('exercise_type', 'type')
    # ### end Alembic commands ###
